services:
  dataservice:
    build:
      context: ../../src/DataService
      dockerfile: Dockerfile
    container_name: dataservice-container
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ASPNETCORE_URLS=http://+:8082
    networks:
      - backend-network

  authservice:
    build:
      context: ../../src/AuthService
      dockerfile: Dockerfile
    container_name: authservice-container
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ASPNETCORE_URLS=http://+:8086
    networks:
      - backend-network

  gameserver:
    build:
      context: ../../src/GameServer
      dockerfile: Dockerfile
    container_name: gameserver-container
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ASPNETCORE_URLS=http://+:8084
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dataservice
      - authservice
      - gameserver
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge